# Generated by Django 3.2.9 on 2022-01-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='price',
            new_name='buy_price',
        ),
        migrations.AddField(
            model_name='sales',
            name='sell_price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
